#!/usr/bin/perl --
if ($0 ne "buy_cgi_test" and -d "c:/")
{
        exit();  # this allows a perl compile-time check on the PC
}
use strict;
use CGI qw(:standard);
use IO::File;
my %__KeyInputs = (
                 'web_key' => [
                                513,
                                42751
                              ],
                 'macro' => [
                              547,
                              752761
                            ],
                 'spinach' => [
                                647,
                                52761
                              ],
                 'snatch' => [
                               540,
                               652761
                             ],
                 'wk_ie' => [
                              507,
                              32751
                            ]
               );
my %__perlModulesByProduct = (
                            'web_key' => [
                                           'c:/perl/web_key.pl',
                                           'c:/users/nsproul/work/bin/perl/Decorate.pm',
                                           'c:/users/nsproul/work/bin/perl/adynware_server.pm'
                                         ],
                            'spinach' => [
                                           'c:/perl/spinach.pl'
                                         ],
                            'snatch' => [
                                          'e:/users/nsproul/work/bin/perl/snatch.pm'
                                        ],
                            'wk_ie' => [
                                         'c:/perl/wk_ie.pl',
                                         'c:/users/nsproul/work/bin/perl/DecorateIE.pm',
                                         'c:/users/nsproul/work/bin/perl/adynware_server.pm'
                                       ]
                          );
my %__ProductDisplayName = (
                          'web_gen' => 'WebGenerator',
                          'web_key' => 'Web Keyboard',
                          'macro' => 'PC Macro32',
                          'ies' => 'ISP Web Hosting Evaluation Service',
                          'lvs_corporate' => 'Corporate Link Verification Service',
                          'wk_ie' => 'Web Keyboard for IE',
                          'lvs' => 'Link Verification Service',
                          'teacher' => 'Teacher',
                          'ies_corporate' => 'Corporate ISP Web Hosting Evaluation Service'
                        );
my %__ProductPrices = (
                     'web_gen' => '75.00',
                     'web_key' => '27.95',
                     'macro' => '9.95',
                     'ies' => '30.00',
                     'lvs_corporate' => '30.00',
                     'wk_ie' => '9.95',
                     'lvs' => '15.00',
                     'teacher' => '19.95',
                     'ies_corporate' => '60.00'
                   );
sub GenerateKey
{
        my($product, $customerID) = @_;
        my $valueReference = $__KeyInputs{$product};
        return undef unless defined $valueReference;
        my @values = @$valueReference;
        return ($customerID * $values[0]) +  $values[1];
}

	my $customerID = 0;
	my $product = 0;
	while (@ARGV)
	{
	  $_ = shift @ARGV;
	  if (/^-product/)
	  {
	    $product = shift @ARGV;
	  }
	  elsif (/^-customerID/)
	  {
	    $customerID = shift @ARGV;
	  }
	  else
	  {
	    die "buy_cgi_test: did not understand $_";
	  }
	}
	print GenerateKey($product, $customerID);
# perl -w buy_cgi_test -product web_key -customerID 65292
